nome=input("Digite um funionario: ")
empresa=input("Digite a Instituição: ")
qtde_Funcionarios=int(input("Digite a Quantidade de Funcionarios: "))
mediaMensalidade=float(input("Digite a média de Mensalidade:"))
print(nome +" trabalha na empresa " + empresa)
print("Possui: ", qtde_Funcionarios,  "funcionarios")
print("A media da mensalidade é de : " + str(mediaMensalidade))
print("===================Verifique os tipos de dados abaixo==========================")
print("O tipo de vriavel [nome] é: ", type (nome))
print("O tipo de vriavel [empresa] é: ", type (empresa))
print("O tipo de vriavel [qtde_Funcionarios] é: ", type (qtde_Funcionarios))
print("O tipo de vriavel [mediaMensalidade] é: ", type (mediaMensalidade))
